import os
from dotenv import load_dotenv

SERVICE_NAME = 'WA-MAIN-WEBHOOK'

environment = os.getenv('ENVIRONMENT','')

load_dotenv(dotenv_path=f"{environment}.env")

REDIS_QUEUE = 'send_pdfs_queue'
REDIS_PORT = 6379
REDIS_DB_ID = 0
REDIS_IP = os.getenv('REDIS_IP','redis')
SERVER_SLEEP = 0.05

DN_PATTERN = r'^(\+52)?(\d{10})$'
EMAIL_PATTERN = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
TRIP_TYPE_PATTERN = r'^(sencillo|redondo)$'

LOGGING_URL = os.getenv('LOGGING_URL','')
QUADIENT_URL = os.getenv('QUADIENT_URL','')

print("Logging URL:" + LOGGING_URL)
print("Quadient URL:" + QUADIENT_URL)

TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID','')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN','')

TWILIO_CONTENT_START_MSID   = 'HXc99717fe32a1d8a960855aa5b78fab39'
TWILIO_CONTENT_SENDPDF_MSID ='HX27c5fe9041e6873335a70333f1f91edb'
TWILIO_CONTENT_NOPENDING_MSID = 'HX76ac9709d3d4b63fde6426a409fb798f'
TWILIO_WHATSAPP_SENDER      = 'whatsapp:+5215539242554'
TWLIO_MSG_SERVICE_SID       = 'MGfa5b6732b046616de08b0ffc40345268'

CLOUDANT_URL = os.getenv('CLOUDANT_URL','')
CLOUDANT_USER = os.getenv('CLOUDANT_USER','')
CLOUDANT_APIKEY = os.getenv('CLOUDANT_APIKEY','')
CLOUDANT_TICKET_DOCUMENTS_DB = os.getenv('CLOUDANT_TICKET_DOCUMENTS_DB','test')

LABEL_CRITICAL = 'CRITICAL'
LABEL_ERROR = 'ERROR'
LABEL_WARNING = 'WARNING'
LABEL_INFO = 'INFO'
LABEL_DEBUG = 'DEBUG'

