FROM python:3.11

RUN mkdir -p /home/wa_history

WORKDIR /home/wa_history

# Install requirements file so the python app can run as usual
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

ENV PYTHONPATH=$PYTHONPATH:/home/wa_history
WORKDIR /home/wa_history

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]



